[package]
name = "cppr"
authors = ["Rahul M. Navneeth <rahulmnavneeth@gmail.com>"]
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A simple C++ package manager"
repository = "https://github.com/RahulNavneeth/cppr"

[dependencies]
